'use strict';

const { mix, alpha } = require('./color');

const TRANSPARENT = '#00000000';

/** Workbench colours — every surface VS Code lets a theme paint. */
function workbench(p) {
  const { ui, status: st, syntax: sx, ansi } = p;
  const dark = p.type === 'dark';
  const a = (hex, v) => alpha(hex, v);
  // Brights: nudge toward the foreground on dark, toward ink on light.
  const bright = (hex) => (dark ? mix(hex, '#FFFFFF', 0.18) : mix(hex, '#000000', 0.14));
  const shadow = dark ? '#0000004D' : a(mix(ui.fg, ui.deep, 0.5), 0.18);
  const onBannerHover = a(ui.onBanner, 0.12);

  return {
    // ── Base
    focusBorder: a(ui.accent, 0.6),
    foreground: ui.fg,
    disabledForeground: ui.fgSubtle,
    descriptionForeground: ui.fgMuted,
    errorForeground: st.error,
    'icon.foreground': ui.fgMuted,
    'widget.border': ui.border,
    'widget.shadow': shadow,
    'selection.background': a(ui.accent, dark ? 0.4 : 0.3),
    'sash.hoverBorder': a(ui.accent, 0.6),
    'contrastBorder': TRANSPARENT,
    'textLink.foreground': sx.link,
    'textLink.activeForeground': ui.accent,
    'textBlockQuote.background': ui.side,
    'textBlockQuote.border': a(ui.accent, 0.5),
    'textCodeBlock.background': ui.side,
    'textPreformat.foreground': sx.string,
    'textPreformat.background': a(ui.fg, 0.06),
    'textSeparator.foreground': ui.border,
    'toolbar.hoverBackground': a(ui.fg, 0.08),
    'toolbar.activeBackground': a(ui.fg, 0.12),

    // ── Title bar
    // The banner: title bar + status bar frame the window in house colours
    'titleBar.activeBackground': ui.banner,
    'titleBar.activeForeground': ui.onBanner,
    'titleBar.inactiveBackground': mix(ui.banner, ui.deep, 0.45),
    'titleBar.inactiveForeground': a(ui.onBanner, 0.7),
    'titleBar.border': ui.banner,
    'commandCenter.background': a(ui.onBanner, 0.08),
    'commandCenter.foreground': ui.onBanner,
    'commandCenter.activeBackground': a(ui.onBanner, 0.14),
    'commandCenter.activeForeground': ui.onBanner,
    'commandCenter.border': a(ui.onBanner, 0.22),
    'commandCenter.activeBorder': a(ui.onBanner, 0.4),
    'commandCenter.inactiveForeground': a(ui.onBanner, 0.7),
    'commandCenter.inactiveBorder': a(ui.onBanner, 0.15),
    'menubar.selectionBackground': onBannerHover,
    'menubar.selectionForeground': ui.onBanner,
    'menu.background': ui.raised,
    'menu.foreground': ui.fg,
    'menu.selectionBackground': a(ui.accent, dark ? 0.3 : 0.2),
    'menu.selectionForeground': ui.fg,
    'menu.separatorBackground': ui.border,
    'menu.border': ui.border,

    // ── Activity bar
    'activityBar.background': ui.deep,
    'activityBar.foreground': ui.accent2,
    'activityBar.inactiveForeground': ui.fgSubtle,
    'activityBar.activeBorder': ui.accent,
    'activityBar.activeBackground': a(ui.accent, 0.08),
    'activityBar.border': ui.border,
    'activityBarBadge.background': ui.button,
    'activityBarBadge.foreground': ui.onButton,
    'activityBarTop.foreground': ui.accent2,
    'activityBarTop.activeBorder': ui.accent,
    'activityBarTop.inactiveForeground': ui.fgSubtle,

    // ── Sidebar
    'sideBar.background': ui.side,
    'sideBar.foreground': ui.fgMuted,
    'sideBar.border': ui.border,
    'sideBarTitle.foreground': ui.fgMuted,
    'sideBarSectionHeader.background': ui.side,
    'sideBarSectionHeader.foreground': ui.fg,
    'sideBarSectionHeader.border': ui.border,
    'sideBar.dropBackground': a(ui.accent, 0.15),

    // ── Lists & trees
    'list.activeSelectionBackground': ui.highlight,
    'list.activeSelectionForeground': ui.fg,
    'list.activeSelectionIconForeground': ui.fg,
    'list.inactiveSelectionBackground': mix(ui.side, ui.highlight, 0.55),
    'list.inactiveSelectionForeground': ui.fg,
    'list.hoverBackground': a(ui.fg, 0.05),
    'list.hoverForeground': ui.fg,
    'list.focusBackground': ui.highlight,
    'list.focusForeground': ui.fg,
    'list.focusOutline': a(ui.accent, 0.5),
    'list.focusAndSelectionOutline': a(ui.accent, 0.5),
    'list.highlightForeground': ui.accent2,
    'list.focusHighlightForeground': ui.accent2,
    'list.dropBackground': a(ui.accent, 0.15),
    'list.errorForeground': st.error,
    'list.warningForeground': st.warning,
    'list.invalidItemForeground': st.error,
    'list.deemphasizedForeground': ui.fgSubtle,
    'listFilterWidget.background': ui.raised,
    'listFilterWidget.outline': a(ui.accent, 0.5),
    'listFilterWidget.noMatchesOutline': st.error,
    'tree.indentGuidesStroke': a(ui.fg, 0.14),
    'tree.inactiveIndentGuidesStroke': a(ui.fg, 0.07),

    // ── Tabs & editor groups
    'editorGroup.border': ui.border,
    'editorGroup.dropBackground': a(ui.accent, 0.12),
    'editorGroupHeader.tabsBackground': ui.side,
    'editorGroupHeader.tabsBorder': ui.border,
    'editorGroupHeader.noTabsBackground': ui.bg,
    'tab.activeBackground': ui.bg,
    'tab.activeForeground': ui.fg,
    'tab.activeBorder': ui.bg,
    'tab.activeBorderTop': ui.accent,
    'tab.inactiveBackground': ui.side,
    'tab.inactiveForeground': ui.fgSubtle,
    'tab.unfocusedActiveBackground': ui.bg,
    'tab.unfocusedActiveForeground': ui.fgMuted,
    'tab.unfocusedActiveBorderTop': a(ui.accent, 0.4),
    'tab.unfocusedInactiveForeground': ui.fgSubtle,
    'tab.hoverBackground': mix(ui.side, ui.bg, 0.5),
    'tab.hoverForeground': ui.fgMuted,
    'tab.border': ui.side,
    'tab.lastPinnedBorder': ui.border,
    'tab.activeModifiedBorder': ui.accent2,
    'tab.inactiveModifiedBorder': a(ui.accent2, 0.5),
    'breadcrumb.background': ui.bg,
    'breadcrumb.foreground': ui.fgSubtle,
    'breadcrumb.focusForeground': ui.fg,
    'breadcrumb.activeSelectionForeground': ui.accent2,
    'breadcrumbPicker.background': ui.raised,

    // ── Editor
    'editor.background': ui.bg,
    'editor.foreground': ui.fg,
    'editorLineNumber.foreground': a(ui.fgSubtle, 0.7),
    'editorLineNumber.activeForeground': ui.accent2,
    'editorLineNumber.dimmedForeground': a(ui.fgSubtle, 0.4),
    'editorCursor.foreground': ui.accent2,
    'editorCursor.background': ui.bg,
    'editor.lineHighlightBackground': ui.lift,
    'editor.lineHighlightBorder': TRANSPARENT,
    'editor.selectionBackground': a(ui.accent, dark ? 0.32 : 0.24),
    'editor.inactiveSelectionBackground': a(ui.accent, dark ? 0.16 : 0.12),
    'editor.selectionHighlightBackground': a(ui.accent, dark ? 0.16 : 0.12),
    'editor.selectionHighlightBorder': TRANSPARENT,
    'editor.wordHighlightBackground': a(ui.fg, 0.08),
    'editor.wordHighlightStrongBackground': a(ui.accent2, 0.16),
    'editor.wordHighlightTextBackground': a(ui.fg, 0.08),
    'editor.findMatchBackground': a(ui.accent2, dark ? 0.4 : 0.35),
    'editor.findMatchBorder': ui.accent2,
    'editor.findMatchHighlightBackground': a(ui.accent2, dark ? 0.2 : 0.18),
    'editor.findRangeHighlightBackground': a(ui.fg, 0.05),
    'editor.rangeHighlightBackground': a(ui.accent, 0.08),
    'editor.hoverHighlightBackground': a(ui.accent, 0.12),
    'editor.linkedEditingBackground': a(ui.accent, 0.12),
    'editor.foldBackground': a(ui.accent, 0.06),
    'editor.snippetTabstopHighlightBackground': a(ui.accent2, 0.15),
    'editor.stackFrameHighlightBackground': a(st.warning, 0.14),
    'editor.focusedStackFrameHighlightBackground': a(st.added, 0.14),
    'editorWhitespace.foreground': a(ui.fg, 0.14),
    'editorIndentGuide.background1': a(ui.fg, 0.07),
    'editorIndentGuide.activeBackground1': a(ui.fg, 0.2),
    'editorRuler.foreground': a(ui.fg, 0.07),
    'editorCodeLens.foreground': ui.fgSubtle,
    'editorLink.activeForeground': sx.link,
    'editorBracketMatch.background': a(ui.accent2, 0.14),
    'editorBracketMatch.border': a(ui.accent2, 0.5),
    'editorBracketHighlight.foreground1': sx.func,
    'editorBracketHighlight.foreground2': sx.keyword,
    'editorBracketHighlight.foreground3': sx.type,
    'editorBracketHighlight.foreground4': sx.string,
    'editorBracketHighlight.foreground5': sx.number,
    'editorBracketHighlight.foreground6': sx.constant,
    'editorBracketHighlight.unexpectedBracket.foreground': st.error,
    'editorBracketPairGuide.activeBackground1': a(sx.func, 0.4),
    'editorBracketPairGuide.activeBackground2': a(sx.keyword, 0.4),
    'editorBracketPairGuide.activeBackground3': a(sx.type, 0.4),
    'editorBracketPairGuide.activeBackground4': a(sx.string, 0.4),
    'editorBracketPairGuide.activeBackground5': a(sx.number, 0.4),
    'editorBracketPairGuide.activeBackground6': a(sx.constant, 0.4),
    'editorInlayHint.background': a(ui.fg, 0.05),
    'editorInlayHint.foreground': ui.fgSubtle,
    'editorGhostText.foreground': a(ui.fgMuted, 0.6),
    'editorUnnecessaryCode.opacity': '#000000A0',
    'editorStickyScroll.background': ui.bg,
    'editorStickyScroll.shadow': shadow,
    'editorStickyScrollHover.background': ui.lift,

    // ── Diagnostics
    'editorError.foreground': st.error,
    'editorWarning.foreground': st.warning,
    'editorInfo.foreground': st.info,
    'editorHint.foreground': ui.fgMuted,
    'problemsErrorIcon.foreground': st.error,
    'problemsWarningIcon.foreground': st.warning,
    'problemsInfoIcon.foreground': st.info,
    'editorLightBulb.foreground': ui.accent2,
    'editorLightBulbAutoFix.foreground': sx.func,

    // ── Gutter & overview ruler
    'editorGutter.background': ui.bg,
    'editorGutter.addedBackground': a(st.added, 0.8),
    'editorGutter.modifiedBackground': a(st.modified, 0.8),
    'editorGutter.deletedBackground': a(st.deleted, 0.8),
    'editorGutter.foldingControlForeground': ui.fgSubtle,
    'editorOverviewRuler.border': TRANSPARENT,
    'editorOverviewRuler.addedForeground': a(st.added, 0.6),
    'editorOverviewRuler.modifiedForeground': a(st.modified, 0.6),
    'editorOverviewRuler.deletedForeground': a(st.deleted, 0.6),
    'editorOverviewRuler.errorForeground': a(st.error, 0.8),
    'editorOverviewRuler.warningForeground': a(st.warning, 0.7),
    'editorOverviewRuler.infoForeground': a(st.info, 0.6),
    'editorOverviewRuler.findMatchForeground': a(ui.accent2, 0.7),
    'editorOverviewRuler.selectionHighlightForeground': a(ui.accent, 0.5),
    'editorOverviewRuler.bracketMatchForeground': a(ui.accent2, 0.5),

    // ── Widgets: suggest, hover, find, peek
    'editorWidget.background': ui.raised,
    'editorWidget.foreground': ui.fg,
    'editorWidget.border': ui.border,
    'editorWidget.resizeBorder': a(ui.accent, 0.6),
    'editorSuggestWidget.background': ui.raised,
    'editorSuggestWidget.border': ui.border,
    'editorSuggestWidget.foreground': ui.fgMuted,
    'editorSuggestWidget.selectedBackground': ui.highlight,
    'editorSuggestWidget.selectedForeground': ui.fg,
    'editorSuggestWidget.highlightForeground': ui.accent2,
    'editorSuggestWidget.focusHighlightForeground': ui.accent2,
    'editorHoverWidget.background': ui.raised,
    'editorHoverWidget.border': ui.border,
    'editorHoverWidget.statusBarBackground': ui.side,
    'debugExceptionWidget.background': ui.raised,
    'debugExceptionWidget.border': st.error,
    'editorMarkerNavigation.background': ui.raised,
    'editorMarkerNavigationError.background': st.error,
    'editorMarkerNavigationWarning.background': st.warning,
    'editorMarkerNavigationInfo.background': st.info,
    'peekView.border': a(ui.accent, 0.6),
    'peekViewTitle.background': ui.side,
    'peekViewTitleLabel.foreground': ui.fg,
    'peekViewTitleDescription.foreground': ui.fgMuted,
    'peekViewEditor.background': mix(ui.bg, ui.side, 0.5),
    'peekViewEditorGutter.background': mix(ui.bg, ui.side, 0.5),
    'peekViewEditor.matchHighlightBackground': a(ui.accent2, 0.3),
    'peekViewResult.background': ui.side,
    'peekViewResult.fileForeground': ui.fg,
    'peekViewResult.lineForeground': ui.fgMuted,
    'peekViewResult.selectionBackground': a(ui.accent, 0.22),
    'peekViewResult.selectionForeground': ui.fg,
    'peekViewResult.matchHighlightBackground': a(ui.accent2, 0.3),

    // ── Inputs, dropdowns, buttons, checkboxes
    'input.background': mix(ui.bg, ui.side, dark ? 0.6 : 0),
    'input.foreground': ui.fg,
    'input.border': ui.border,
    'input.placeholderForeground': ui.fgSubtle,
    'inputOption.activeBackground': a(ui.accent, 0.25),
    'inputOption.activeBorder': a(ui.accent, 0.6),
    'inputOption.activeForeground': ui.fg,
    'inputValidation.errorBackground': mix(ui.raised, st.error, 0.15),
    'inputValidation.errorBorder': st.error,
    'inputValidation.warningBackground': mix(ui.raised, st.warning, 0.15),
    'inputValidation.warningBorder': st.warning,
    'inputValidation.infoBackground': mix(ui.raised, st.info, 0.15),
    'inputValidation.infoBorder': st.info,
    'dropdown.background': ui.raised,
    'dropdown.listBackground': ui.raised,
    'dropdown.foreground': ui.fg,
    'dropdown.border': ui.border,
    'button.background': ui.button,
    'button.foreground': ui.onButton,
    'button.hoverBackground': mix(ui.button, dark ? '#FFFFFF' : '#000000', 0.08),
    'button.border': TRANSPARENT,
    'button.separator': a(ui.onButton, 0.3),
    'button.secondaryBackground': a(ui.fg, 0.1),
    'button.secondaryForeground': ui.fg,
    'button.secondaryHoverBackground': a(ui.fg, 0.15),
    'checkbox.background': ui.raised,
    'checkbox.border': ui.border,
    'checkbox.foreground': ui.accent2,
    'radio.activeBackground': a(ui.accent, 0.25),
    'radio.activeBorder': ui.accent,
    'badge.background': a(ui.accent, 0.25),
    'badge.foreground': ui.fg,
    'progressBar.background': ui.accent,
    'keybindingLabel.background': a(ui.fg, 0.07),
    'keybindingLabel.foreground': ui.fgMuted,
    'keybindingLabel.border': a(ui.fg, 0.12),
    'keybindingLabel.bottomBorder': a(ui.fg, 0.18),

    // ── Command palette / quick input
    'quickInput.background': ui.raised,
    'quickInput.foreground': ui.fg,
    'quickInputTitle.background': ui.side,
    'quickInputList.focusBackground': ui.highlight,
    'quickInputList.focusForeground': ui.fg,
    'quickInputList.focusIconForeground': ui.fg,
    'pickerGroup.foreground': ui.accent2,
    'pickerGroup.border': ui.border,

    // ── Scrollbar & minimap
    'scrollbar.shadow': shadow,
    'scrollbarSlider.background': a(ui.fg, 0.1),
    'scrollbarSlider.hoverBackground': a(ui.fg, 0.16),
    'scrollbarSlider.activeBackground': a(ui.accent, 0.4),
    'minimap.background': ui.bg,
    'minimap.selectionHighlight': a(ui.accent, 0.5),
    'minimap.findMatchHighlight': a(ui.accent2, 0.6),
    'minimap.errorHighlight': a(st.error, 0.7),
    'minimap.warningHighlight': a(st.warning, 0.7),
    'minimapSlider.background': a(ui.fg, 0.06),
    'minimapSlider.hoverBackground': a(ui.fg, 0.1),
    'minimapSlider.activeBackground': a(ui.fg, 0.14),
    'minimapGutter.addedBackground': st.added,
    'minimapGutter.modifiedBackground': st.modified,
    'minimapGutter.deletedBackground': st.deleted,

    // ── Panel & terminal
    'panel.background': ui.side,
    'panel.border': ui.border,
    'panel.dropBorder': ui.accent,
    'panelTitle.activeForeground': ui.fg,
    'panelTitle.activeBorder': ui.accent,
    'panelTitle.inactiveForeground': ui.fgSubtle,
    'panelInput.border': ui.border,
    'panelSection.border': ui.border,
    'panelSectionHeader.background': ui.side,
    'outputView.background': ui.side,
    'terminal.background': ui.side,
    'terminal.foreground': ui.fg,
    'terminal.border': ui.border,
    'terminal.selectionBackground': a(ui.accent, dark ? 0.32 : 0.24),
    'terminal.inactiveSelectionBackground': a(ui.accent, 0.14),
    'terminal.findMatchBackground': a(ui.accent2, 0.4),
    'terminal.findMatchHighlightBackground': a(ui.accent2, 0.2),
    'terminalCursor.foreground': ui.accent2,
    'terminal.dropBackground': a(ui.accent, 0.15),
    'terminalCommandDecoration.defaultBackground': ui.fgSubtle,
    'terminalCommandDecoration.successBackground': st.added,
    'terminalCommandDecoration.errorBackground': st.error,
    'terminal.ansiBlack': ansi.black,
    'terminal.ansiRed': ansi.red,
    'terminal.ansiGreen': ansi.green,
    'terminal.ansiYellow': ansi.yellow,
    'terminal.ansiBlue': ansi.blue,
    'terminal.ansiMagenta': ansi.magenta,
    'terminal.ansiCyan': ansi.cyan,
    'terminal.ansiWhite': ansi.white,
    'terminal.ansiBrightBlack': dark ? mix(ansi.black, ui.fg, 0.3) : ui.fgSubtle,
    'terminal.ansiBrightRed': bright(ansi.red),
    'terminal.ansiBrightGreen': bright(ansi.green),
    'terminal.ansiBrightYellow': bright(ansi.yellow),
    'terminal.ansiBrightBlue': bright(ansi.blue),
    'terminal.ansiBrightMagenta': bright(ansi.magenta),
    'terminal.ansiBrightCyan': bright(ansi.cyan),
    'terminal.ansiBrightWhite': dark ? mix(ansi.white, '#FFFFFF', 0.3) : mix(ansi.white, ui.bg, 0.5),

    // ── Status bar — the house signature
    'statusBar.background': ui.banner,
    'statusBar.foreground': ui.onBanner,
    'statusBar.border': ui.banner,
    'statusBar.focusBorder': ui.onBanner,
    'statusBar.noFolderBackground': ui.banner,
    'statusBar.noFolderForeground': ui.onBanner,
    'statusBar.noFolderBorder': ui.banner,
    'statusBar.debuggingBackground': ui.accent2,
    'statusBar.debuggingForeground': dark ? ui.deep : ui.onButton,
    'statusBar.debuggingBorder': ui.accent2,
    'statusBarItem.remoteBackground': a(ui.onBanner, 0.16),
    'statusBarItem.remoteForeground': ui.onBanner,
    'statusBarItem.remoteHoverBackground': a(ui.onBanner, 0.24),
    'statusBarItem.hoverBackground': onBannerHover,
    'statusBarItem.hoverForeground': ui.onBanner,
    'statusBarItem.activeBackground': a(ui.onBanner, 0.2),
    'statusBarItem.prominentBackground': a(ui.onBanner, 0.16),
    'statusBarItem.prominentForeground': ui.onBanner,
    'statusBarItem.prominentHoverBackground': a(ui.onBanner, 0.24),
    'statusBarItem.errorBackground': dark ? '#9E3A36' : '#B83A34',
    'statusBarItem.errorForeground': '#FFF4F0',
    'statusBarItem.warningBackground': dark ? '#8A6418' : '#9A6400',
    'statusBarItem.warningForeground': '#FFF8EC',

    // ── Notifications & banners
    'notifications.background': ui.raised,
    'notifications.foreground': ui.fg,
    'notifications.border': ui.border,
    'notificationCenterHeader.background': ui.side,
    'notificationCenterHeader.foreground': ui.fgMuted,
    'notificationToast.border': ui.border,
    'notificationLink.foreground': sx.link,
    'notificationsErrorIcon.foreground': st.error,
    'notificationsWarningIcon.foreground': st.warning,
    'notificationsInfoIcon.foreground': st.info,
    'banner.background': ui.raised,
    'banner.foreground': ui.fg,
    'banner.iconForeground': ui.accent2,

    // ── Git decorations, diff, merge
    'gitDecoration.addedResourceForeground': st.added,
    'gitDecoration.untrackedResourceForeground': st.added,
    'gitDecoration.modifiedResourceForeground': st.modified,
    'gitDecoration.stageModifiedResourceForeground': st.modified,
    'gitDecoration.deletedResourceForeground': st.deleted,
    'gitDecoration.stageDeletedResourceForeground': st.deleted,
    'gitDecoration.renamedResourceForeground': sx.regex,
    'gitDecoration.conflictingResourceForeground': st.warning,
    'gitDecoration.ignoredResourceForeground': ui.fgSubtle,
    'gitDecoration.submoduleResourceForeground': ui.accent2,
    'diffEditor.insertedTextBackground': a(st.added, dark ? 0.14 : 0.16),
    'diffEditor.insertedLineBackground': a(st.added, dark ? 0.08 : 0.09),
    'diffEditor.removedTextBackground': a(st.deleted, dark ? 0.16 : 0.16),
    'diffEditor.removedLineBackground': a(st.deleted, dark ? 0.08 : 0.08),
    'diffEditor.border': ui.border,
    'diffEditor.diagonalFill': a(ui.fg, 0.07),
    'diffEditorGutter.insertedLineBackground': a(st.added, 0.18),
    'diffEditorGutter.removedLineBackground': a(st.deleted, 0.18),
    'merge.currentHeaderBackground': a(st.added, 0.35),
    'merge.currentContentBackground': a(st.added, 0.12),
    'merge.incomingHeaderBackground': a(st.info, 0.35),
    'merge.incomingContentBackground': a(st.info, 0.12),
    'merge.commonHeaderBackground': a(ui.fg, 0.2),
    'merge.commonContentBackground': a(ui.fg, 0.06),
    'scmGraph.historyItemHoverLabelForeground': ui.onButton,
    'scmGraph.foreground1': ui.accent,
    'scmGraph.foreground2': ui.accent2,
    'scmGraph.foreground3': sx.func,
    'scmGraph.foreground4': sx.string,
    'scmGraph.foreground5': sx.constant,

    // ── Debugging & testing
    'debugToolBar.background': ui.raised,
    'debugToolBar.border': ui.border,
    'debugIcon.breakpointForeground': st.error,
    'debugIcon.breakpointDisabledForeground': a(st.error, 0.5),
    'debugIcon.breakpointCurrentStackframeForeground': st.warning,
    'debugIcon.startForeground': st.added,
    'debugIcon.pauseForeground': st.warning,
    'debugIcon.stopForeground': st.error,
    'debugIcon.restartForeground': st.added,
    'debugIcon.stepOverForeground': st.info,
    'debugIcon.stepIntoForeground': st.info,
    'debugIcon.stepOutForeground': st.info,
    'debugIcon.continueForeground': st.info,
    'debugTokenExpression.name': sx.property,
    'debugTokenExpression.value': ui.fgMuted,
    'debugTokenExpression.string': sx.string,
    'debugTokenExpression.number': sx.number,
    'debugTokenExpression.boolean': sx.constant,
    'debugTokenExpression.error': st.error,
    'debugConsole.infoForeground': st.info,
    'debugConsole.warningForeground': st.warning,
    'debugConsole.errorForeground': st.error,
    'debugConsole.sourceForeground': ui.fgMuted,
    'testing.iconPassed': st.added,
    'testing.iconFailed': st.error,
    'testing.iconErrored': st.error,
    'testing.iconQueued': st.warning,
    'testing.iconSkipped': ui.fgSubtle,
    'testing.runAction': st.added,

    // ── Symbols in outline / breadcrumbs / suggest
    'symbolIcon.classForeground': sx.type,
    'symbolIcon.interfaceForeground': sx.type,
    'symbolIcon.structForeground': sx.type,
    'symbolIcon.enumeratorForeground': sx.type,
    'symbolIcon.enumeratorMemberForeground': sx.constant,
    'symbolIcon.functionForeground': sx.func,
    'symbolIcon.methodForeground': sx.func,
    'symbolIcon.constructorForeground': sx.func,
    'symbolIcon.variableForeground': sx.variable,
    'symbolIcon.constantForeground': sx.constant,
    'symbolIcon.propertyForeground': sx.property,
    'symbolIcon.fieldForeground': sx.property,
    'symbolIcon.keywordForeground': sx.keyword,
    'symbolIcon.stringForeground': sx.string,
    'symbolIcon.numberForeground': sx.number,
    'symbolIcon.booleanForeground': sx.constant,
    'symbolIcon.moduleForeground': sx.keyword,
    'symbolIcon.namespaceForeground': sx.keyword,
    'symbolIcon.typeParameterForeground': sx.type,
    'symbolIcon.snippetForeground': ui.accent2,

    // ── Misc
    'settings.headerForeground': ui.fg,
    'settings.modifiedItemIndicator': ui.accent2,
    'settings.focusedRowBackground': a(ui.fg, 0.04),
    'welcomePage.tileBackground': ui.side,
    'welcomePage.tileHoverBackground': ui.lift,
    'walkThrough.embeddedEditorBackground': ui.side,
    'extensionButton.prominentBackground': ui.button,
    'extensionButton.prominentForeground': ui.onButton,
    'extensionButton.prominentHoverBackground': mix(ui.button, dark ? '#FFFFFF' : '#000000', 0.08),
    'extensionBadge.remoteBackground': ui.button,
    'extensionBadge.remoteForeground': ui.onButton,
    'extensionIcon.starForeground': ui.accent2,
    'charts.foreground': ui.fgMuted,
    'charts.lines': ui.border,
    'charts.red': st.error,
    'charts.blue': st.info,
    'charts.yellow': st.warning,
    'charts.orange': sx.number,
    'charts.green': st.added,
    'charts.purple': sx.constant,
    'chat.requestBackground': a(ui.fg, 0.03),
    'chat.requestBorder': ui.border,
    'chat.slashCommandBackground': a(ui.accent, 0.2),
    'chat.slashCommandForeground': ui.fg,
    'inlineChat.background': ui.raised,
    'inlineChat.border': ui.border,
  };
}

/** TextMate scopes — covers JS/TS, Python, SQL, JSON, HTML/CSS, Markdown, Go, Rust, shell and more. */
function tokenColors(p) {
  const s = p.syntax;
  const rule = (name, scope, foreground, fontStyle) => ({
    name,
    scope,
    settings: fontStyle === undefined ? { foreground } : { foreground, fontStyle },
  });

  return [
    rule('Comments', ['comment', 'punctuation.definition.comment', 'string.comment'], s.comment, 'italic'),
    rule('Doc comment tags', ['storage.type.class.jsdoc', 'entity.name.type.instance.jsdoc', 'keyword.other.phpdoc', 'comment.block.documentation storage'], s.keyword, 'italic'),
    rule('Doc comment names', ['variable.other.jsdoc', 'comment.block.documentation variable'], s.param, 'italic'),

    rule('Keywords & storage', [
      'keyword', 'storage.type', 'storage.modifier', 'keyword.control', 'keyword.other.using',
      'keyword.other.operator', 'keyword.operator.new', 'keyword.operator.expression',
      'keyword.operator.logical.python', 'keyword.operator.wordlike', 'keyword.other.DML.sql',
      'keyword.other.sql', 'variable.language.this', 'variable.language.self', 'variable.language.super',
      'variable.parameter.function.language.special.self.python',
    ], s.keyword, ''),
    rule('Operators', ['keyword.operator', 'punctuation.accessor', 'punctuation.separator.key-value', 'storage.type.function.arrow'], s.operator, ''),
    rule('Punctuation', [
      'punctuation', 'meta.brace', 'punctuation.definition.parameters', 'punctuation.definition.block',
      'punctuation.separator', 'punctuation.terminator', 'meta.delimiter',
    ], s.punct),

    rule('Functions', [
      'entity.name.function', 'meta.function-call entity.name.function', 'support.function',
      'meta.function-call.generic', 'variable.function', 'entity.name.function.macro',
      'support.function.builtin', 'keyword.other.special-method',
    ], s.func),
    rule('Types & classes', [
      'entity.name.type', 'entity.name.class', 'entity.other.inherited-class', 'support.class',
      'support.type', 'entity.name.namespace', 'entity.name.type.module', 'storage.type.primitive',
      'storage.type.built-in', 'support.type.primitive', 'entity.name.type.parameter',
      'meta.return-type', 'storage.type.sql', 'support.type.python',
    ], s.type),
    rule('Decorators & annotations', [
      'meta.decorator', 'entity.name.function.decorator', 'punctuation.decorator',
      'storage.type.annotation', 'meta.attribute.rust',
    ], s.escape),

    rule('Variables', ['variable', 'variable.other', 'variable.other.readwrite', 'meta.definition.variable'], s.variable),
    rule('Parameters', ['variable.parameter', 'meta.parameter', 'variable.parameter.function'], s.param),
    rule('Properties', [
      'variable.other.property', 'variable.other.object.property', 'meta.object-literal.key',
      'support.variable.property', 'entity.name.tag.yaml', 'meta.property-name',
      'variable.other.member', 'entity.name.variable.field',
    ], s.property),
    rule('Constants', [
      'constant', 'constant.language', 'support.constant', 'variable.other.constant',
      'variable.other.enummember', 'constant.other.symbol',
    ], s.constant),
    rule('Numbers', ['constant.numeric', 'keyword.other.unit', 'constant.other.color'], s.number),

    rule('Strings', ['string', 'string.quoted', 'string.template', 'string.unquoted', 'markup.inline.raw.string'], s.string),
    rule('Template expressions', ['punctuation.definition.template-expression', 'punctuation.section.embedded'], s.keyword),
    rule('Template inner', ['meta.template.expression', 'meta.embedded.line'], s.variable),
    rule('Escapes & placeholders', ['constant.character.escape', 'constant.other.placeholder', 'constant.character.format.placeholder'], s.escape),
    rule('Regex', ['string.regexp', 'constant.other.character-class.regexp', 'keyword.operator.quantifier.regexp'], s.regex),

    // HTML / JSX / XML
    rule('Tags', ['entity.name.tag', 'support.class.component', 'meta.tag.sgml.doctype'], s.tag),
    rule('Tag brackets', ['punctuation.definition.tag'], s.punct),
    rule('Attributes', ['entity.other.attribute-name'], s.attr),
    rule('Attribute ids/classes', ['entity.other.attribute-name.id', 'entity.other.attribute-name.class.css'], s.func),

    // CSS
    rule('CSS properties', ['support.type.property-name.css', 'support.type.vendored.property-name', 'support.type.property-name.scss'], s.property),
    rule('CSS values', ['support.constant.property-value', 'support.constant.font-name', 'support.constant.color'], s.constant),
    rule('CSS selectors', ['entity.name.tag.css', 'entity.other.attribute-name.pseudo-class', 'entity.other.attribute-name.pseudo-element'], s.tag),
    rule('CSS variables', ['variable.css', 'variable.argument.css', 'variable.scss', 'support.type.custom-property'], s.param),

    // JSON — nested keys fade through the palette so structure reads at a glance
    rule('JSON keys', ['support.type.property-name.json'], s.property),
    rule('JSON keys 2', ['meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json'], s.func),
    rule('JSON keys 3', ['meta.structure.dictionary.value.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json'], s.type),

    // Markdown
    rule('Headings', ['markup.heading', 'entity.name.section.markdown', 'markup.heading punctuation.definition.heading'], s.heading, 'bold'),
    rule('Bold', ['markup.bold'], s.number, 'bold'),
    rule('Italic', ['markup.italic'], s.param, 'italic'),
    rule('Strikethrough', ['markup.strikethrough'], s.comment, 'strikethrough'),
    rule('Links', ['markup.underline.link', 'string.other.link', 'markup.link'], s.link),
    rule('Link text', ['string.other.link.title.markdown', 'string.other.link.description.markdown'], s.func),
    rule('Inline code', ['markup.inline.raw', 'markup.fenced_code.block.markdown punctuation.definition', 'markup.raw'], s.string),
    rule('Quotes', ['markup.quote'], s.comment, 'italic'),
    rule('Lists', ['punctuation.definition.list.begin.markdown', 'beginning.punctuation.definition.list.markdown'], s.keyword),
    rule('Separator', ['meta.separator.markdown'], s.comment),

    // Diffs
    rule('Diff inserted', ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'], p.status.added),
    rule('Diff deleted', ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'], p.status.deleted),
    rule('Diff changed', ['markup.changed', 'punctuation.definition.changed'], p.status.modified),
    rule('Diff range', ['meta.diff.range', 'meta.diff.header'], s.keyword),

    // Shell, env, ini, toml, yaml
    rule('Shell variables', ['variable.other.normal.shell', 'variable.other.special.shell', 'punctuation.definition.variable.shell'], s.param),
    rule('Shell commands', ['entity.name.command.shell', 'support.function.builtin.shell'], s.func),
    rule('Env / ini keys', ['variable.other.env', 'keyword.other.definition.ini', 'support.type.property-name.toml'], s.property),
    rule('YAML anchors', ['entity.name.type.anchor.yaml', 'variable.other.alias.yaml'], s.constant),
    rule('Sections', ['entity.name.section.group-title.ini', 'support.type.property-name.table.toml'], s.keyword),

    // Python specifics
    rule('Python f-string braces', ['constant.character.format.placeholder.other.python', 'storage.type.format.python'], s.escape),
    rule('Python magic', ['support.variable.magic.python', 'support.function.magic.python'], s.constant),

    // SQL specifics
    rule('SQL functions', ['support.function.aggregate.sql', 'support.function.scalar.sql'], s.func),
    rule('SQL tables', ['constant.other.table-name.sql', 'constant.other.database-name.sql'], s.type),

    // Rust / Go / C-family
    rule('Lifetimes & macros', ['storage.modifier.lifetime.rust', 'entity.name.lifetime.rust'], s.constant, 'italic'),
    rule('Preprocessor', ['meta.preprocessor', 'keyword.control.directive', 'punctuation.definition.directive'], s.escape),
    rule('Package names', ['entity.name.package.go', 'entity.name.import.go'], s.type),

    rule('Invalid', ['invalid', 'invalid.illegal'], p.status.error),
    rule('Deprecated', ['invalid.deprecated'], p.status.warning, 'strikethrough'),
  ];
}

/** Semantic highlighting keeps the same meaning across every language server. */
function semanticTokenColors(p) {
  const s = p.syntax;
  return {
    namespace: s.type,
    class: s.type,
    enum: s.type,
    interface: s.type,
    struct: s.type,
    type: s.type,
    typeParameter: s.type,
    'class.defaultLibrary': s.type,
    function: s.func,
    method: s.func,
    macro: s.func,
    'function.defaultLibrary': s.func,
    decorator: s.escape,
    variable: s.variable,
    'variable.readonly': s.constant,
    'variable.defaultLibrary': s.constant,
    'variable.readonly.local': s.variable,
    parameter: s.param,
    property: s.property,
    'property.readonly': s.property,
    enumMember: s.constant,
    event: s.property,
    keyword: s.keyword,
    selfKeyword: s.keyword,
    number: s.number,
    string: s.string,
    regexp: s.regex,
    comment: { foreground: s.comment, italic: true },
    '*.deprecated': { strikethrough: true },
    lifetime: { foreground: s.constant, italic: true },
    builtinConstant: s.constant,
  };
}

function buildTheme(p) {
  return {
    $schema: 'vscode://schemas/color-theme',
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    colors: workbench(p),
    tokenColors: tokenColors(p),
    semanticTokenColors: semanticTokenColors(p),
  };
}

module.exports = { buildTheme };
